// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: api/proto/machine.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineStatusResponse) Reset() {
	*x = MachineStatusResponse{}
	mi := &file_api_proto_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineStatusResponse) ProtoMessage() {}

func (x *MachineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineStatusResponse.ProtoReflect.Descriptor instead.
func (*MachineStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MachineStatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_machine_proto protoreflect.FileDescriptor

const file_api_proto_machine_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/machine.proto\x12\x12openmachinecore.v1\x1a\x16api/proto/common.proto\"K\n" +
	"\x15MachineStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\xcb\x01\n" +
	"\x0eMachineService\x12Y\n" +
	"\tGetStatus\x12!.openmachinecore.v1.StatusRequest\x1a).openmachinecore.v1.MachineStatusResponse\x12^\n" +
	"\fStreamStatus\x12!.openmachinecore.v1.StatusRequest\x1a).openmachinecore.v1.MachineStatusResponse0\x01B6Z4github.com/KevinKickass/OpenMachineCore/api/proto/v1b\x06proto3"

var (
	file_api_proto_machine_proto_rawDescOnce sync.Once
	file_api_proto_machine_proto_rawDescData []byte
)

func file_api_proto_machine_proto_rawDescGZIP() []byte {
	file_api_proto_machine_proto_rawDescOnce.Do(func() {
		file_api_proto_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_machine_proto_rawDesc), len(file_api_proto_machine_proto_rawDesc)))
	})
	return file_api_proto_machine_proto_rawDescData
}

var file_api_proto_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_machine_proto_goTypes = []any{
	(*MachineStatusResponse)(nil), // 0: openmachinecore.v1.MachineStatusResponse
	(*StatusRequest)(nil),         // 1: openmachinecore.v1.StatusRequest
}
var file_api_proto_machine_proto_depIdxs = []int32{
	1, // 0: openmachinecore.v1.MachineService.GetStatus:input_type -> openmachinecore.v1.StatusRequest
	1, // 1: openmachinecore.v1.MachineService.StreamStatus:input_type -> openmachinecore.v1.StatusRequest
	0, // 2: openmachinecore.v1.MachineService.GetStatus:output_type -> openmachinecore.v1.MachineStatusResponse
	0, // 3: openmachinecore.v1.MachineService.StreamStatus:output_type -> openmachinecore.v1.MachineStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_machine_proto_init() }
func file_api_proto_machine_proto_init() {
	if File_api_proto_machine_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_machine_proto_rawDesc), len(file_api_proto_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_machine_proto_goTypes,
		DependencyIndexes: file_api_proto_machine_proto_depIdxs,
		MessageInfos:      file_api_proto_machine_proto_msgTypes,
	}.Build()
	File_api_proto_machine_proto = out.File
	file_api_proto_machine_proto_goTypes = nil
	file_api_proto_machine_proto_depIdxs = nil
}
