// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: api/proto/system.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	State          string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	UpdateProgress *UpdateProgress        `protobuf:"bytes,2,opt,name=update_progress,json=updateProgress,proto3" json:"update_progress,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemStatus) Reset() {
	*x = SystemStatus{}
	mi := &file_api_proto_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatus) ProtoMessage() {}

func (x *SystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatus.ProtoReflect.Descriptor instead.
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_system_proto_rawDescGZIP(), []int{0}
}

func (x *SystemStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SystemStatus) GetUpdateProgress() *UpdateProgress {
	if x != nil {
		return x.UpdateProgress
	}
	return nil
}

func (x *SystemStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UpdateProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgress) Reset() {
	*x = UpdateProgress{}
	mi := &file_api_proto_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgress) ProtoMessage() {}

func (x *UpdateProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgress.ProtoReflect.Descriptor instead.
func (*UpdateProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_system_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *UpdateProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *UpdateProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowPath  string                 `protobuf:"bytes,1,opt,name=workflow_path,json=workflowPath,proto3" json:"workflow_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_proto_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_system_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetWorkflowPath() string {
	if x != nil {
		return x.WorkflowPath
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_proto_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_system_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_system_proto protoreflect.FileDescriptor

const file_api_proto_system_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/system.proto\x12\x12openmachinecore.v1\x1a\x16api/proto/common.proto\"\x8f\x01\n" +
	"\fSystemStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12K\n" +
	"\x0fupdate_progress\x18\x02 \x01(\v2\".openmachinecore.v1.UpdateProgressR\x0eupdateProgress\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\\\n" +
	"\x0eUpdateProgress\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"4\n" +
	"\rUpdateRequest\x12#\n" +
	"\rworkflow_path\x18\x01 \x01(\tR\fworkflowPath\"D\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x90\x02\n" +
	"\rSystemService\x12U\n" +
	"\fStreamStatus\x12!.openmachinecore.v1.StatusRequest\x1a .openmachinecore.v1.SystemStatus0\x01\x12V\n" +
	"\rTriggerUpdate\x12!.openmachinecore.v1.UpdateRequest\x1a\".openmachinecore.v1.UpdateResponse\x12P\n" +
	"\tGetStatus\x12!.openmachinecore.v1.StatusRequest\x1a .openmachinecore.v1.SystemStatusB6Z4github.com/KevinKickass/OpenMachineCore/api/proto/v1b\x06proto3"

var (
	file_api_proto_system_proto_rawDescOnce sync.Once
	file_api_proto_system_proto_rawDescData []byte
)

func file_api_proto_system_proto_rawDescGZIP() []byte {
	file_api_proto_system_proto_rawDescOnce.Do(func() {
		file_api_proto_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_system_proto_rawDesc), len(file_api_proto_system_proto_rawDesc)))
	})
	return file_api_proto_system_proto_rawDescData
}

var file_api_proto_system_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_system_proto_goTypes = []any{
	(*SystemStatus)(nil),   // 0: openmachinecore.v1.SystemStatus
	(*UpdateProgress)(nil), // 1: openmachinecore.v1.UpdateProgress
	(*UpdateRequest)(nil),  // 2: openmachinecore.v1.UpdateRequest
	(*UpdateResponse)(nil), // 3: openmachinecore.v1.UpdateResponse
	(*StatusRequest)(nil),  // 4: openmachinecore.v1.StatusRequest
}
var file_api_proto_system_proto_depIdxs = []int32{
	1, // 0: openmachinecore.v1.SystemStatus.update_progress:type_name -> openmachinecore.v1.UpdateProgress
	4, // 1: openmachinecore.v1.SystemService.StreamStatus:input_type -> openmachinecore.v1.StatusRequest
	2, // 2: openmachinecore.v1.SystemService.TriggerUpdate:input_type -> openmachinecore.v1.UpdateRequest
	4, // 3: openmachinecore.v1.SystemService.GetStatus:input_type -> openmachinecore.v1.StatusRequest
	0, // 4: openmachinecore.v1.SystemService.StreamStatus:output_type -> openmachinecore.v1.SystemStatus
	3, // 5: openmachinecore.v1.SystemService.TriggerUpdate:output_type -> openmachinecore.v1.UpdateResponse
	0, // 6: openmachinecore.v1.SystemService.GetStatus:output_type -> openmachinecore.v1.SystemStatus
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_system_proto_init() }
func file_api_proto_system_proto_init() {
	if File_api_proto_system_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_system_proto_rawDesc), len(file_api_proto_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_system_proto_goTypes,
		DependencyIndexes: file_api_proto_system_proto_depIdxs,
		MessageInfos:      file_api_proto_system_proto_msgTypes,
	}.Build()
	File_api_proto_system_proto = out.File
	file_api_proto_system_proto_goTypes = nil
	file_api_proto_system_proto_depIdxs = nil
}
